site_name: Tutorials CEFIRE FP
site_author: Cefire FP
site_url: https://cefirefp.github.io/docs/
docs_dir: 'md'
site_dir: 'docs'
#repo_url: https://github.com/cefirefp/cefirefp.github.io #para mostrar un link al repositorio
#repo_name: cefirefp.github.io

edit_uri: '' #Suprimir el icono de edición (https://www.mkdocs.org/user-guide/configuration/#edit_uri)

nav:
  - Inici: index.md
  - Paper de l'assessor/a: assessor.md
  - Organització: organitzacio.md
  - Gestió Administrativa: gestio_administrativa.md
  - Gestió Formacions:
      - 📑 Índex: gestio_formacions.md
      - 📝 Disseny de la formació: gestioformacions/disseny.md
      - ⚙️ Generar la formació: gestioformacions/generar.md
      - 🛠️ Preparar la formació: gestioformacions/preparar.md
      - 👀 Seguiment de la formació: gestioformacions/seguiment.md
      - 🎓 Certificació i tancament de la formació: gestioformacions/certificacio_tancament.md
  - Perfils:
      - FSE: perfil/fse.md
      - Skills: perfil/skills.md
      - PAA: perfil/paa.md
  - Gestió Econòmica:
      - Comprova estat de la gestió econòmica de la formació: gestioeconomica/ge_comprova.md  
      - Protocol de minutes: gestioeconomica/ge_protocolo_general_minutas.md
      - Protocol de factures: gestioeconomica/ge_protocolo_general_facturas.md
      - Finalització de les formacions: gestioeconomica/ge_finalizacion_curso.md
  - Gestió ERESAR: eresar.md
  - PAF: paf.md
  - Tutorials:
      - Gesform: tutorials/tutorial_gesform.md
      - Creació de sessió en Teams: tutorials/tutorial_teams.md
      - Recuperar contrasenya Aules: tutorials/tutorial_recuperar_contrasenya_aules.md
  #- 📄 Descarregar PDF: pdf/documentacion.pdf


theme:
  name: material
  include_search_page: false
  font:
    code: Roboto
    text: Baloo 2
  palette:
    # Boto que canvia a mode oscur
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Canvia a mode fosc
    # Botó que canvia a mode clar
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Canvia a mode clar
  favicon: images/icono.jpg
  features:
    - header.autohide
    - toc.follow  # el toc segueix en la pantalla
    - toc.integrate # el toc dins de la pàgina, en el menu lateral
    - search.suggest
    #- navigation.tabs
    #- navigation.tabs.sticky
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.footer       # footer de la pagina, amb navegació
    - navigation.top          # boto flotant de tornar a dalt 
    - content.footnote.tooltips
    - mermaid
  logo: images/icono.jpg
  icon:
    admonition:
      note: octicons/alert-24
      example: octicons/book-16
  

extra_css:
  - css/extra.css

extra:
  generator: false #Muestra en el pie de página que se ha realiza
  social:
    - icon: material/file-pdf-box
      link: pdf/documentacion.pdf
      name: Descargar PDF


markdown_extensions:
    - sane_lists
    - abbr
    - admonition
    - attr_list
    - def_list
    - footnotes
    - md_in_html
    - toc:
        permalink: true
        toc_depth: 3
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.blocks.caption #permet afegir captions a les imatges
    - pymdownx.caret #permet afegir text amb subíndex i superíndex
    - pymdownx.details #permet afegir detalls desplegables
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.keys #permet afegir text amb l'aparença de tecla
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format 
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

plugins:
  - search
  - macros:
      include_yaml:
        - variables.yml
  # - with-pdf:
  #     output_path: pdf/documentacion.pdf
  #     cover_logo: images/icono.jpg
  #     cover_title: "Tutorials CEFIRE FP"
  #     cover_subtitle: "Cefire Formació Professional"
  #     back_cover: true
  #     toc_title: "Índex" #Canvia el títol de l'índex
  #     toc_level: 3 #Nivell de títols que apareixen en l'índex
  #     ordered_chapters_level: 2 #Nivell de títols que es numeraran
  #     page_numbers: true
  #     show_anchors: true
  #     verbose: true #Mostra missatges de depuració a la consola   

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
